// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL5pVap6cEj91XYBWEiP2kwKuzQYGOc_I',
    appId: '1:788332295504:web:32fbcf66747e293a5c2855',
    messagingSenderId: '788332295504',
    projectId: 'dailymind-6aa95',
    authDomain: 'dailymind-6aa95.firebaseapp.com',
    storageBucket: 'dailymind-6aa95.firebasestorage.app',
    measurementId: 'G-8DE3C1V023',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL5pVap6cEj91XYBWEiP2kwKuzQYGOc_I',
    appId: '1:788332295504:android:XXXXXXXXXX',
    messagingSenderId: '788332295504',
    projectId: 'dailymind-6aa95',
    storageBucket: 'dailymind-6aa95.firebasestorage.app',
  );
}